/*
 * jpeg_rebuilder.cpp – Reconstruct a JPEG from the three files produced by jpeg_splitter.cpp
 *
 *   Inputs  (big‑endian values):
 *       <base>.hdr   – JPEG header through first SOS (no entropy data)
 *       <base>.dc    – DC coefficients, one 16‑bit BE value per block
 *       <base>.ac    – AC coefficients, 63× 16‑bit BE values per block
 *   Output:
 *       <output.jpg> – Compressed JPEG regenerated by libjpeg
 *
 * Build: g++ jpeg_rebuilder.cpp -o jpeg_rebuilder -ljpeg
 * Usage:
 *   1) Explicit paths:
 *        ./jpeg_rebuilder in.hdr in.dc in.ac out.jpg
 *   2) Base‑name shortcut (reads base.hdr/.dc/.ac):
 *        ./jpeg_rebuilder base  out.jpg
 */

#include <iostream>
#include <fstream>
#include <vector>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <jpeglib.h>
#include <setjmp.h>

//------------------------------------------------------------------
//  libjpeg error handling helper
//------------------------------------------------------------------
struct my_error_mgr {
    jpeg_error_mgr pub;
    jmp_buf setjmp_buffer;
};
using my_error_ptr = my_error_mgr*;

extern "C" {
    static void my_error_exit(j_common_ptr cinfo) {
        my_error_ptr myerr = reinterpret_cast<my_error_ptr>(cinfo->err);
        (*cinfo->err->output_message)(cinfo);
        longjmp(myerr->setjmp_buffer, 1);
    }
}

//------------------------------------------------------------------
//  Helper – read 16‑bit big‑endian signed value
//------------------------------------------------------------------
static inline int16_t read_be16(std::ifstream& in) {
    unsigned char b[2];
    in.read(reinterpret_cast<char*>(b), 2);
    if (in.gcount() != 2)
        throw std::runtime_error("Unexpected EOF while reading 16‑bit value");
    return static_cast<int16_t>((b[0] << 8) | b[1]);
}

//------------------------------------------------------------------
//  Helper – read entire file into vector
//------------------------------------------------------------------
static std::vector<unsigned char> slurp(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) throw std::runtime_error("Cannot open " + path);
    f.seekg(0, std::ios::end);
    std::streamoff sz = f.tellg();
    f.seekg(0, std::ios::beg);
    std::vector<unsigned char> buf(static_cast<size_t>(sz));
    f.read(reinterpret_cast<char*>(buf.data()), sz);
    if (f.gcount() != sz) throw std::runtime_error("Short read on " + path);
    return buf;
}

//------------------------------------------------------------------
//  Main
//------------------------------------------------------------------
int main(int argc, char** argv) {
    std::string hdr_path, dc_path, ac_path, out_path;

    if (argc == 5) {
        hdr_path = argv[1];
        dc_path  = argv[2];
        ac_path  = argv[3];
        out_path = argv[4];
    } else if (argc == 3) {
        std::string base = argv[1];
        hdr_path = base + ".hdr";
        dc_path  = base + ".dc";
        ac_path  = base + ".ac";
        out_path = argv[2];
    } else {
        std::cerr << "Usage: " << argv[0] << " <hdr> <dc> <ac> <out.jpg>\n";
        std::cerr << "   or  : " << argv[0] << " <base> <out.jpg>\n";
        return 1;
    }

    //------------------------------------------------------------------
    // 1. Parse header with a temporary decompressor
    //------------------------------------------------------------------
    std::vector<unsigned char> hdr_buf;
    try { hdr_buf = slurp(hdr_path); }
    catch (const std::exception& e) { std::cerr << e.what() << std::endl; return 1; }

    jpeg_decompress_struct srcinfo{};
    my_error_mgr jerr_src;
    srcinfo.err = jpeg_std_error(&jerr_src.pub);
    jerr_src.pub.error_exit = my_error_exit;

    if (setjmp(jerr_src.setjmp_buffer)) {
        jpeg_destroy_decompress(&srcinfo);
        std::cerr << "Error parsing header." << std::endl;
        return 1;
    }

    jpeg_create_decompress(&srcinfo);
    jpeg_mem_src(&srcinfo, hdr_buf.data(), static_cast<unsigned long>(hdr_buf.size()));
    jpeg_read_header(&srcinfo, TRUE);
    std::cout << "before read_coefficients: "<< std::endl;

    jvirt_barray_ptr* dummy = jpeg_read_coefficients(&srcinfo); // fix for DNL issue
    std::cout << "after read_coefficients: "<< std::endl;
    //------------------------------------------------------------------
    // 2. Create compressor and copy parameters
    //------------------------------------------------------------------
    jpeg_compress_struct dstinfo{};
    my_error_mgr jerr_dst;
    dstinfo.err = jpeg_std_error(&jerr_dst.pub);
    jerr_dst.pub.error_exit = my_error_exit;

    if (setjmp(jerr_dst.setjmp_buffer)) {
        jpeg_destroy_compress(&dstinfo);
        jpeg_destroy_decompress(&srcinfo);
        std::cerr << "Compression error." << std::endl;
        return 1;
    }

    jpeg_create_compress(&dstinfo);
    jpeg_copy_critical_parameters(&srcinfo, &dstinfo);
    jpeg_calc_jpeg_dimensions(&dstinfo);
    std::cout << "Copied critical parameters from decompressor to compressor." << std::endl;
    //------------------------------------------------------------------
    // 3. Allocate virtual coeff arrays in the compressor
    //------------------------------------------------------------------
    jvirt_barray_ptr* coef_arrays = reinterpret_cast<jvirt_barray_ptr*>(
        dstinfo.mem->alloc_small((j_common_ptr)&dstinfo, JPOOL_IMAGE,
                                  sizeof(jvirt_barray_ptr) * dstinfo.num_components));

    for (int comp = 0; comp < dstinfo.num_components; ++comp) {
        jpeg_component_info* ci = dstinfo.comp_info + comp;
        std::cout << "Allocating virtual barray for component " << comp
                  << ": width=" << ci->width_in_blocks
                  << ", height=" << ci->height_in_blocks << std::endl;
        coef_arrays[comp] = dstinfo.mem->request_virt_barray(
            (j_common_ptr)&dstinfo, JPOOL_IMAGE, TRUE,
            ci->width_in_blocks, ci->height_in_blocks, (JDIMENSION)1);
    }
    std::cout << "Allocated virtual coefficient arrays for compressor." << std::endl;
    //------------------------------------------------------------------
    // 4. Load DC & AC streams
    //------------------------------------------------------------------
    std::ifstream dc_in(dc_path, std::ios::binary);
    if (!dc_in) { std::cerr << "Cannot open " << dc_path << std::endl; return 1; }
    std::ifstream ac_in(ac_path, std::ios::binary);
    if (!ac_in) { std::cerr << "Cannot open " << ac_path << std::endl; return 1; }

    try {
        for (int comp = 0; comp < dstinfo.num_components; ++comp) {
            jpeg_component_info* ci = dstinfo.comp_info + comp;
            for (JDIMENSION row = 0; row < ci->height_in_blocks; ++row) {
                JBLOCKARRAY rowptr = dstinfo.mem->access_virt_barray(
                    (j_common_ptr)&dstinfo, coef_arrays[comp], row, 1, TRUE);
                for (JDIMENSION col = 0; col < ci->width_in_blocks; ++col) {
                    JBLOCK* blk = &rowptr[0][col];
                    // blk is pointer to an array[64]; use (*blk)[i]
                    (*blk)[0] = read_be16(dc_in);
                    for (int k = 1; k < DCTSIZE2; ++k) {
                        (*blk)[k] = read_be16(ac_in);
                    }
                }
            }
        }
    }
    catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        return 1;
    }

    dc_in.close();
    ac_in.close();
    std::cout << "Loaded DC and AC coefficients." << std::endl;
    //------------------------------------------------------------------
    // 5. Write out compressed JPEG
    //------------------------------------------------------------------
    FILE* outfile = std::fopen(out_path.c_str(), "wb");
    if (!outfile) { std::cerr << "Cannot create " << out_path << std::endl; return 1; }
    jpeg_stdio_dest(&dstinfo, outfile);

    jpeg_write_coefficients(&dstinfo, coef_arrays);
    jpeg_finish_compress(&dstinfo);
    std::cout << "Wrote coefficients and finished compression." << std::endl;
    //------------------------------------------------------------------
    // 6. Cleanup
    //------------------------------------------------------------------
    jpeg_destroy_compress(&dstinfo);
    jpeg_destroy_decompress(&srcinfo);
    std::fclose(outfile);

    std::cout << "Rebuilt JPEG saved to " << out_path << std::endl;
    return 0;
}
